name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Paso para realizar el checkout del código

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Especifica la versión de Python que deseas usar

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias desde requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests  # Ejecuta las pruebas unitarias
